

# Fonts
font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono
italic_font      JetBrainsMono Nerd Font Mono
bold_italic_font JetBrainsMono Nerd Font MOno

font_size	13
disable_ligatures never
copy_on_select yes

open_url_with default

background_opacity 0.9

# Performance
sync_to_monitor yes
repaint_delay    							20
mouse_hide_wait 0.0

window_padding_width 8
placement_strategy top-left
enable_audio_bell yes

shell_integration disabled
 
# Keys
map ctrl+v              					paste_from_clipboard
map ctrl+equal           					increase_font_size
map ctrl+minus        	    			    decrease_font_size
map ctrl+backspace 	    	    	        restore_font_size

cursor_shape underline
cursor_underline_thickness 4.0
cursor_stop_blinking_after 15.0
focus_follows_mouse no

# BEGIN_KITTY_THEME
# One Dark
include aquarium.conf
# END_KITTY_THEME
