#!/bin/sh
pamixer "$@"

volume="$(pamixer --get-volume-human)"

if [ "$volume" = "muted" ]; then
    notify-send -r 69  -a "Volume" "Muted"  -i ~/.config/dunst/assets/volume.svg -t 888 -u low
else
    notify-send -r 69 -a "Volume" "Currently at $volume" -h int:value:"$volume" -i ~/.config/dunst/assets/volume.svg  -t 888 -u low
fi
