#! /bin/sh

$HOME/.config/polybar/launch.sh  &


# Fix BSPWM bug with Jetbrains App (fucking soydev)
export _JAVA_AWT_WM_NONREPARENTING=1
wm_name LG3D


bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	true


# Pointer
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


# Set the border colors.
bspc config normal_border_color "#1e1d2d"
bspc config focused_border_color "#A4B9EF"


# Window Rules
bspc rule -a Screenkey manage=off

bspc rule -a Google-chrome desktop='^1' follow=on
bspc rule -a code-oss='^3' follow=on
bspc rule -a Thunar desktop='^4' follow=on
bspc rule -a discord desktop='^7' follow=on
bspc rule -a android-studio state=floating border=off follow=on
bspc rule -a Sxiv desktop='^5' follow=on


