 
;================================================
; VOLUME WITH PULSEAUDIO
;================================================
[module/pulseaudio]
type = internal/pulseaudio

format-volume-padding = 0
format-volume = <ramp-volume> <bar-volume>
format-volume-background = ${colors.light-bg}
format-volume-foreground = ${colors.yellow}
use-ui-max = false
interval = 5

ramp-volume-0 = "%{T3} "
ramp-volume-1 = "%{T3} "
ramp-volume-2 = "%{T3}"


label-muted = %{T3}%{T1} MUTED
label-muted-background = ${colors.light-bg}
label-muted-foreground = ${colors.red}
label-muted-padding = 0


bar-volume-width = 10
bar-volume-fill = %{T5}•
bar-volume-foreground-0 = ${colors.yellow}
bar-volume-foreground-1 = ${colors.yellow}
bar-volume-foreground-2 = ${colors.yellow}
bar-volume-foreground-3 = ${colors.yellow}
bar-volume-foreground-4 = ${colors.yellow}
bar-volume-foreground-5 = ${colors.yellow}
bar-volume-foreground-6 = ${colors.yellow}
bar-volume-fill-foreground = #61afef
bar-volume-fill-font = 2
bar-volume-empty = %{T5}•
bar-volume-empty-font = 2
bar-volume-empty-foreground = #4c5664
bar-volume-indicator =  

[module/battery]
type = internal/battery
full-at = 99
low-at = 15
; $ ls -1 /sys/class/power_supply/
battery = ${system-battery.battery}
adapter = ${system-battery.adapter}
poll-interval = 2

format-charging = <animation-charging> <label-charging>
format-charging-foreground = #a0a8b6
format-charging-padding = 2

format-charging-background = #2c2e3e

format-discharging = <ramp-capacity> <label-discharging>
format-discharging-foreground = #8791a3
format-discharging-background = #2c2e3e
format-discharging-padding = 2

format-full = <ramp-capacity> <label-full>
format-full-padding = 2
format-full-foreground = #A3BE8C
format-full-background = #2c2e3e

label-charging = "%percentage%%"
label-charging-foreground = 
label-discharging = "%percentage%%"
label-discharging-foreground = #a0a8b6
label-full = 100%

ramp-capacity-0 = %{T3}
ramp-capacity-1 = %{T3}
ramp-capacity-2 = %{T3}
ramp-capacity-3 = %{T3}
ramp-capacity-4 = %{T3}
ramp-capacity-5 = %{T3}
ramp-capacity-6 = %{T3}

ramp-capacity-0-foreground = #caf6bb
ramp-capacity-1-foreground = #caf6bb
ramp-capacity-2-foreground = #caf6bb
ramp-capacity-3-foreground = #caf6bb
ramp-capacity-4-foreground = #caf6bb
ramp-capacity-5-foreground = #caf6bb
ramp-capacity-6-foreground = #caf6bb

animation-charging-0 = %{T3}
animation-charging-foreground = #caf6bb

animation-charging-framerate = 750

[module/bsplayout]
type = internal/bspwm
;format-suffix = %{Fcolors.shade7}|%{F-}

format = <label-mode>
pin-workspace = false

enable-scroll = false
inline-mode = false

label-monocle-overline =    ${colors.light-bg}
label-tiled-overline =      ${colors.light-bg}
label-monocle-underline =   ${colors.light-bg}
label-tiled-underline =     ${colors.light-bg}
format-background =         ${colors.light-bg}
format-foreground =         ${colors.light-fg}


label-monocle = 
label-tiled = 
label-floating = 
label-marked = 
label-locked = 
label-sticky = 
label-private = 
label-pseudotiled = 

label-monocle-padding = 1
label-tiled-padding = 1
label-floating-padding = 1
label-locked-padding = 1
label-pseudotiled-padding = 1
label-sticky-padding = 1

[module/time]
type = internal/date
interval = 60
format = <label>
format-background = ${colors.light-bg}
format-foreground = ${colors.cyan}
time = %{T3}%{T1} %I:%M %p%
date-alt =  %a, %b %d%{F-}
label = %time%%date%

[module/bspwm]
type = internal/bspwm
pin-workspaces = true
inline-mode = true
enable-click = true
enable-scroll = true
reverse-scroll = false

format = <label-state> <label-mode>
; workspaces names
ws-icon-0 = 1;%{F#ebe3b9}%{T7}
ws-icon-1 = 2;%{F#ebb9b9}%{T3}
ws-icon-2 = 3;%{F#cddbf9}%{T3}
ws-icon-3 = 4;%{F#f6bbe7}%{T3}
ws-icon-4 = 5;%{F#caf6bb}%{T3}
ws-icon-5 = 6;%{F#E8CCA7}%{T3}
ws-icon-6 = 7;%{F#cddbf9}
ws-icon-7 = 8;%{F#44495e}

label-focused = %icon%
label-focused-background = ${colors.light-bg}
label-focused-foreground = ${colors.magenta}
label-focused-underline = ${colors.magenta}
label-focused-padding = 1

label-occupied = %icon%
label-occupied-background = ${colors.light-bg}
label-occupied-foreground = ${colors.cyan}
label-occupied-underline = ${colors.cyan}
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = ${colors.light-bg}
label-urgent-foreground = ${colors.red}
label-urgent-underline = ${colors.red}
label-urgent-padding =1

label-empty = %icon%
label-empty-foreground = ${colors.fg}
label-empty-background = ${colors.light-bg}
label-empty-padding = 1

label-separator = " "
label-separator-background = ${colors.light-bg}

  
[module/cpu]
type = internal/cpu
interval = 3
format = <label>
label = %percentage%%

format-prefix = "%{T3}%{T1} "
format-padding = 0
format-background = ${colors.light-bg}
format-foreground = ${colors.cyan}

[module/memory]
type = custom/script
exec = free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p'
format = <label>
format-prefix = "%{T3}%{T1} "
label = %output% MB
format-foreground = ${colors.red}
;label-padding = 1
format-padding = 0
format-prefix-foreground = ${colors.red}
format-background = ${colors.light-bg}


[module/updates]
type = custom/script
exec = ~/.config/polybar/scripts/updates
interval = 600
label = "%{T3}%{T1} %output%"
format-foreground = ${colors.green}
format-foreground-error = ${colors.red}
format-background = ${colors.light-bg}
click-left = kitty -e $SHELL -c 'sudo pacman -Syu'
click-right = bspc rule -a \* -o state=floating ; sleep 0.015 ; kitty -e $SHELL -c 'yay -Qu | less'
 
[module/mpd]
type = internal/mpd
format-online = "%{T1}<label-song> <bar-progress> "
label-song =  %title%
label-offline =
label-song-maxlen = 22
format-online-foreground = #E6DFB8
label-song-foreground = #f6bbe7
format-online-margin = 1

bar-progress-width = 10
bar-progress-indicator =
bar-progress-fill = %{T6}─
bar-progress-fill-foreground = #E6DFB8
bar-progress-empty = %{T6}─
bar-progress-empty-foreground = #2c2e3e




[module/wlan]
type = internal/network
interface = ${system-wifi.interface}
interval = 3.0
format-connected =  <label-connected>
label-connected = "%{T0}直 connected"
label-disconnected = "%{T0}睊 no signal"
label-connected-foreground = ${colors.cyan}
label-disconnected-foreground = ${colors.red}
label-connected-margin = 1
label-disconnected-margin = 1

[module/network-down]
type = internal/network
interface = ${system-ethernet.interface}
interval = 1
label-connected = " %{T3}  %{T1}%downspeed%"
label-connected-foreground = ${colors.green}
label-disconnected = disconnected

[module/network-up]
type = internal/network
interface = ${system-ethernet.interface}
interval = 1
label-connected = "%{T3}  %{T1}%upspeed% "
label-connected-foreground = ${colors.red}
label-disconnected = disconnected


[module/backlight]
type = internal/xbacklight
card = intel_backlight
format = <ramp> <label>
format-foreground = #cddbf9
format-background = #2c2e3e
format-padding = 2
label = %percentage%%
ramp-0 = %{T3}
ramp-1 = %{T3}
ramp-2 = %{T3}


; requires radeontop 
[module/gpu]
type = custom/script
interval = 3
exec = ~/.config/polybar/scripts/amdgpu_usage
tail = true
format-prefix = "%{T3}%{T1} "
format="<label>%"
format-foreground = ${colors.magenta}
format-background = ${colors.light-bg}

[module/temp]
type = internal/temperature
hwmon-path = /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input
warn-temperature = 70
label-foreground =  ${colors.yellow} 
format = <ramp> <label>
;format-underline = #b48ead 
format-warn = <ramp>  <label-warn>
format-background = ${colors.light-bg}

label = %temperature-c%
label-warn = %temperature-c%

format-padding = 0 
ramp-0 = "%{T3} %{T1}"
ramp-foreground = ${colors.yellow} 

[module/dunst]
type = custom/ipc
initial = 1
format-foreground = #ebe3b9
format-background = #2c2e3e
;format-padding = 1
hook-0 = echo "%{A1:notify-send "DUNST_COMMAND_PAUSE" && polybar-msg hook dunst 2:}  %{A}" &
hook-1 = echo "%{A1:notify-send "DUNST_COMMAND_RESUME" && polybar-msg hook dunst 1:} %{F#3b4252}%{F-} %{A}" &
click-middle = rofi_notif_center.sh &
